import React from "react";
import Navbar from "../components/Navbar";
import Placeholder from "../components/Shop/Placeholder";
import dynamic from 'next/dynamic';
const DynamicProduct=dynamic(()=>import('../components/Shop/Product'),{
  loading: () => <Placeholder/> ,
  ssr: false,
})

const products=[
  {
    img:'../product.jpg',
    fav:true,
    offer:true,
    oPrice:100000,
    nPrice:70000,
    rating:"4.5"
  },
  {
    img:'../product.jpg',
    fav:true,
    offer:false,
    oPrice:'',
    nPrice:70000,
    rating:"3.5"
  },
  {
    img:'../product.jpg',
    fav:true,
    offer:true,
    oPrice:100000,
    nPrice:70000,
    rating:"0.5"
  },
  {
    img:'../product.jpg',
    fav:true,
    offer:false,
    oPrice:'',
    nPrice:70000,
    rating:"4.5"
  },
  {
    img:'../product.jpg',
    fav:true,
    offer:true,
    oPrice:100000,
    nPrice:70000,
    rating:"1.5"
  },
  {
    img:'../product.jpg',
    fav:true,
    offer:false,
    oPrice:'',
    nPrice:70000,
    rating:"0"
  },
  {
    img:'../product.jpg',
    fav:true,
    offer:true,
    oPrice:100000,
    nPrice:70000,
    rating:"4.5"
  },
  {
    img:'../product.jpg',
    fav:true,
    offer:false,
    oPrice:"",
    nPrice:70000,
    rating:"5.0"
  },
  {
    img:'../product.jpg',
    fav:true,
    offer:true,
    oPrice:200000,
    nPrice:150000,
    rating:"2.5"
  },
  {
    img:'../product.jpg',
    fav:true,
    offer:true,
    oPrice:100000,
    nPrice:70000,
    rating:"3.0"
  },
  {
    img:'../product.jpg',
    fav:true,
    offer:true,
    oPrice:100000,
    nPrice:70000,
    rating:"4.5"
  },
  {
    img:'../product.jpg',
    fav:true,
    offer:false,
    oPrice:'',
    nPrice:70000,
    rating:"3.5"
  },
  {
    img:'../product.jpg',
    fav:true,
    offer:true,
    oPrice:100000,
    nPrice:70000,
    rating:"0.5"
  },
  {
    img:'../product.jpg',
    fav:true,
    offer:false,
    oPrice:'',
    nPrice:70000,
    rating:"4.5"
  },
  {
    img:'../product.jpg',
    fav:true,
    offer:true,
    oPrice:100000,
    nPrice:70000,
    rating:"1.5"
  },
  {
    img:'../product.jpg',
    fav:true,
    offer:false,
    oPrice:'',
    nPrice:70000,
    rating:"0"
  },
  {
    img:'../product.jpg',
    fav:true,
    offer:true,
    oPrice:100000,
    nPrice:70000,
    rating:"4.5"
  },
  {
    img:'../product.jpg',
    fav:true,
    offer:false,
    oPrice:"",
    nPrice:70000,
    rating:"5.0"
  },
  {
    img:'../product.jpg',
    fav:true,
    offer:true,
    oPrice:200000,
    nPrice:150000,
    rating:"2.5"
  },
  {
    img:'../product.jpg',
    fav:true,
    offer:true,
    oPrice:100000,
    nPrice:70000,
    rating:"3.0"
  },
]

const Favourite = () => {

  return (
    <>
      <Navbar/>
      <div className="w-full min-h-screen pt-28 pb-14 px-4 md:px-8 flex justify-evenly flex-wrap">

        {
          products.map((one,index)=>{
            return <DynamicProduct key={index} id={index}
            img={one.img}
            fav={one.fav}
            offer={one.offer}
            oPrice={one.oPrice}
            nPrice={one.nPrice}
            rating={one.rating}/>
          })
        }
      </div>
    </>
  );
};

export default Favourite;
